# Generated by Django 4.2.5 on 2023-09-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='choice',
            field=models.CharField(default='', max_length=50),
        ),
    ]
